### PR TITLE
Adding OptimalPlanet(2016) to the portfolio

### PR DESCRIPTION
**Pull request by stijnmeijer**

### CODE REVIEW

**Comment by mrngm** [comment]
Hi Stijn,
Can you also remove one of the existing projects from 2015 in `_posts/` in this pull request? After that, I can merge it.

**Comment by stijnmeijer** [comment]
We removed an old project (FixMyBike) and some obsolete project image files as well. Could you please review the changes and merge them?

**Comment by mrngm** [comment]
Looks good, thanks.

**Comment by stijnmeijer** [comment]
Hello, I see {{ site.url }} in _posts/2016-04-22-optimalplanet.md is being replaced by 127.0.0.1:8888 instead of giphouse.nl. Therefore, the logo on our project's information page could not be loaded. Should I replace {{ site.url }} with giphouse.nl?

**Comment by mrngm** [comment]
You should use `{{ site.github.url }}`, apparently (see [here](https://jekyllrb.com/docs/github-pages/)).

**Pull request merged**
